
# Options related to the disconnect timeouts.
[timeouts]
	# The read timeout in seconds.
	# This is the time it takes for a player to be disconnected after not responding to a KeepAlive packet.
	# This value is automatically rounded up to a product of 15.
	# Min: 1
	# Max: 2147483647
	# Default: 90
	readTimeout = 90
	# The login timeout in ticks.
	# Min: 1
	# Max: 2147483647
	# Default: 900
	loginTimeout = 900

# Options that don't fit into any other categories.
[misc]
	# Enables the /rpreload command.
	# Default: true
	rpreload = true

